# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(default=b'', max_length=300)),
                ('costume_type', models.CharField(choices=[(b'Hat', b'Hat'), (b'Pants', b'Pants'), (b'Boots', b'Boots')], default=b'', max_length=300)),
                ('region', models.CharField(blank=True, choices=[(b'KR', b'Krakowski'), (b'LW', b'Lowicki'), (b'SZ', b'Szlachecki'), (b'N', b'None')], max_length=30)),
                ('size', models.CharField(blank=True, choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large')], max_length=30)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'U', b'Unisex')], default=b'U', max_length=1)),
                ('status', models.IntegerField(choices=[(1, b'Available'), (0, b'On loan')], default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Transaction date')),
                ('rent_return', models.IntegerField(choices=[(1, b'Rental'), (0, b'Return')], default=1)),
                ('items', models.ManyToManyField(to='lendingapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingapp.Supplier'),
        ),
    ]
